/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clueLess;
import java.util.Map;
import java.util.HashMap;

/**
 *
 * @author Alisha R. Hunt
 */
public class GameBoard extends javax.swing.JFrame {

    private int gameID;
    private String userID;
    
    /**
     * Creates new form GameBoard
     */
    public GameBoard() {
        initComponents();
        closeRoomSelection();
        
        

        // Creating a map for the room values
        /*Map<String, String> rightHereMap = new HashMap<String, String>()
{
    {
        put("key1", "value1");
        put("key2", "value2");
    }
};*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Welcome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        EnterUserID = new javax.swing.JPanel();
        userIDfield = new javax.swing.JTextField();
        userIDprompt = new javax.swing.JLabel();
        GameOps = new javax.swing.JPanel();
        startNewGameButton = new javax.swing.JButton();
        gameIDfield = new javax.swing.JTextField();
        gameIDprompt = new javax.swing.JLabel();
        Gameboard = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        DNsuspect2 = new javax.swing.JCheckBox();
        DNsuspect1 = new javax.swing.JCheckBox();
        DNsuspect4 = new javax.swing.JCheckBox();
        DNsuspect5 = new javax.swing.JCheckBox();
        DNsuspect3 = new javax.swing.JCheckBox();
        DNsuspect6 = new javax.swing.JCheckBox();
        DNhall = new javax.swing.JCheckBox();
        DNlounge = new javax.swing.JCheckBox();
        DNdiningroom = new javax.swing.JCheckBox();
        DNkitchen = new javax.swing.JCheckBox();
        DNballroom = new javax.swing.JCheckBox();
        DNconservatory = new javax.swing.JCheckBox();
        DNbilliardroom = new javax.swing.JCheckBox();
        DNlibrary = new javax.swing.JCheckBox();
        DNstudy = new javax.swing.JCheckBox();
        DNknife = new javax.swing.JCheckBox();
        DNcandlestick = new javax.swing.JCheckBox();
        DNpistol = new javax.swing.JCheckBox();
        DNrope = new javax.swing.JCheckBox();
        DNleadpipe = new javax.swing.JCheckBox();
        DNwrench = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        Conservatory = new javax.swing.JButton();
        Study = new javax.swing.JButton();
        Library = new javax.swing.JButton();
        Ballroom = new javax.swing.JButton();
        BilliardRoom = new javax.swing.JButton();
        Hall = new javax.swing.JButton();
        Kitchen = new javax.swing.JButton();
        DiningRoom = new javax.swing.JButton();
        Lounge = new javax.swing.JButton();
        Hallway6 = new javax.swing.JButton();
        Hallway1 = new javax.swing.JButton();
        Hallway11 = new javax.swing.JButton();
        Hallway12 = new javax.swing.JButton();
        Hallway7 = new javax.swing.JButton();
        Hallway2 = new javax.swing.JButton();
        Hallway4 = new javax.swing.JButton();
        Hallway3 = new javax.swing.JButton();
        Hallway5 = new javax.swing.JButton();
        Hallway8 = new javax.swing.JButton();
        Hallway9 = new javax.swing.JButton();
        Hallway10 = new javax.swing.JButton();
        Lobby = new javax.swing.JPanel();
        lobbyWelcome = new javax.swing.JLabel();
        startGameBox = new javax.swing.JPanel();
        startGamePrompt = new javax.swing.JLabel();
        startGamePrompt1 = new javax.swing.JLabel();
        startGameButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        playersInLobby = new javax.swing.JList<>();
        Winning = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        Losing = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel4.setFont(new java.awt.Font("Old English Text MT", 0, 60)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome to Clue-Less!!");

        EnterUserID.setBackground(new java.awt.Color(153, 153, 153));
        EnterUserID.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        userIDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDfieldActionPerformed(evt);
            }
        });

        userIDprompt.setText("Enter a name for yourself");

        javax.swing.GroupLayout EnterUserIDLayout = new javax.swing.GroupLayout(EnterUserID);
        EnterUserID.setLayout(EnterUserIDLayout);
        EnterUserIDLayout.setHorizontalGroup(
            EnterUserIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterUserIDLayout.createSequentialGroup()
                .addGroup(EnterUserIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EnterUserIDLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(userIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EnterUserIDLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(userIDprompt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        EnterUserIDLayout.setVerticalGroup(
            EnterUserIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EnterUserIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userIDprompt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(userIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        GameOps.setBackground(new java.awt.Color(153, 153, 153));
        GameOps.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        startNewGameButton.setText("Start a New Game");
        startNewGameButton.setActionCommand("NewGame");
        startNewGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startNewGameButtonActionPerformed(evt);
            }
        });

        gameIDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gameIDfieldActionPerformed(evt);
            }
        });

        gameIDprompt.setText("Or enter an existing Game ID");

        javax.swing.GroupLayout GameOpsLayout = new javax.swing.GroupLayout(GameOps);
        GameOps.setLayout(GameOpsLayout);
        GameOpsLayout.setHorizontalGroup(
            GameOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameOpsLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(gameIDprompt, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameOpsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GameOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameOpsLayout.createSequentialGroup()
                        .addComponent(gameIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GameOpsLayout.createSequentialGroup()
                        .addComponent(startNewGameButton)
                        .addGap(62, 62, 62))))
        );
        GameOpsLayout.setVerticalGroup(
            GameOpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GameOpsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startNewGameButton)
                .addGap(26, 26, 26)
                .addComponent(gameIDprompt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GameOps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EnterUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(GameOps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout WelcomeLayout = new javax.swing.GroupLayout(Welcome);
        Welcome.setLayout(WelcomeLayout);
        WelcomeLayout.setHorizontalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WelcomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        WelcomeLayout.setVerticalGroup(
            WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(557, Short.MAX_VALUE))
            .addGroup(WelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WelcomeLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(Welcome, "card3");

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Notes:");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Your Cards:");

        jList1.setBackground(new java.awt.Color(0, 0, 255));
        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setForeground(new java.awt.Color(255, 153, 153));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("This will be the UI text display box along the bottom.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setForeground(new java.awt.Color(204, 255, 204));
        jLabel1.setText("Detective Notes");

        jLabel8.setForeground(new java.awt.Color(204, 255, 204));
        jLabel8.setText("Suspects:");

        jLabel15.setForeground(new java.awt.Color(204, 255, 204));
        jLabel15.setText("Rooms:");

        jLabel25.setForeground(new java.awt.Color(204, 255, 204));
        jLabel25.setText("Weapons:");

        DNsuspect2.setForeground(new java.awt.Color(255, 102, 102));
        DNsuspect2.setText("Suspect 1");
        DNsuspect2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNsuspect2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNsuspect2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNsuspect2ActionPerformed(evt);
            }
        });

        DNsuspect1.setForeground(new java.awt.Color(204, 0, 0));
        DNsuspect1.setText("Suspect 1");
        DNsuspect1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNsuspect1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNsuspect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNsuspect1ActionPerformed(evt);
            }
        });

        DNsuspect4.setForeground(new java.awt.Color(255, 102, 102));
        DNsuspect4.setText("Suspect 1");
        DNsuspect4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNsuspect4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNsuspect4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNsuspect4ActionPerformed(evt);
            }
        });

        DNsuspect5.setForeground(new java.awt.Color(255, 102, 102));
        DNsuspect5.setText("Suspect 1");
        DNsuspect5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNsuspect5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNsuspect5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNsuspect5ActionPerformed(evt);
            }
        });

        DNsuspect3.setForeground(new java.awt.Color(255, 102, 102));
        DNsuspect3.setText("Suspect 1");
        DNsuspect3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNsuspect3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNsuspect3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNsuspect3ActionPerformed(evt);
            }
        });

        DNsuspect6.setForeground(new java.awt.Color(255, 102, 102));
        DNsuspect6.setText("Suspect 1");
        DNsuspect6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNsuspect6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNsuspect6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNsuspect6ActionPerformed(evt);
            }
        });

        DNhall.setForeground(new java.awt.Color(255, 102, 102));
        DNhall.setText("Hall");
        DNhall.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNhall.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNhall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNhallActionPerformed(evt);
            }
        });

        DNlounge.setForeground(new java.awt.Color(255, 102, 102));
        DNlounge.setText("Lounge");
        DNlounge.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNlounge.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNlounge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNloungeActionPerformed(evt);
            }
        });

        DNdiningroom.setForeground(new java.awt.Color(255, 102, 102));
        DNdiningroom.setText("Dining Room");
        DNdiningroom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNdiningroom.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNdiningroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNdiningroomActionPerformed(evt);
            }
        });

        DNkitchen.setForeground(new java.awt.Color(255, 102, 102));
        DNkitchen.setText("Kitchen");
        DNkitchen.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNkitchen.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNkitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNkitchenActionPerformed(evt);
            }
        });

        DNballroom.setForeground(new java.awt.Color(255, 102, 102));
        DNballroom.setText("Ballroom");
        DNballroom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNballroom.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNballroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNballroomActionPerformed(evt);
            }
        });

        DNconservatory.setForeground(new java.awt.Color(255, 102, 102));
        DNconservatory.setText("Conservatory");
        DNconservatory.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNconservatory.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNconservatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNconservatoryActionPerformed(evt);
            }
        });

        DNbilliardroom.setForeground(new java.awt.Color(255, 102, 102));
        DNbilliardroom.setText("Billiard Room");
        DNbilliardroom.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNbilliardroom.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNbilliardroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNbilliardroomActionPerformed(evt);
            }
        });

        DNlibrary.setForeground(new java.awt.Color(255, 102, 102));
        DNlibrary.setText("Library");
        DNlibrary.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNlibrary.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNlibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNlibraryActionPerformed(evt);
            }
        });

        DNstudy.setForeground(new java.awt.Color(255, 102, 102));
        DNstudy.setText("Study");
        DNstudy.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNstudy.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNstudy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNstudyActionPerformed(evt);
            }
        });

        DNknife.setForeground(new java.awt.Color(255, 102, 102));
        DNknife.setText("Knife");
        DNknife.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNknife.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNknife.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNknifeActionPerformed(evt);
            }
        });

        DNcandlestick.setForeground(new java.awt.Color(255, 102, 102));
        DNcandlestick.setText("Candlestick");
        DNcandlestick.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNcandlestick.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNcandlestick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNcandlestickActionPerformed(evt);
            }
        });

        DNpistol.setForeground(new java.awt.Color(255, 102, 102));
        DNpistol.setText("Pistol");
        DNpistol.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNpistol.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNpistol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNpistolActionPerformed(evt);
            }
        });

        DNrope.setForeground(new java.awt.Color(255, 102, 102));
        DNrope.setText("Rope");
        DNrope.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNrope.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNrope.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNropeActionPerformed(evt);
            }
        });

        DNleadpipe.setForeground(new java.awt.Color(255, 102, 102));
        DNleadpipe.setText("Lead Pipe");
        DNleadpipe.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNleadpipe.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNleadpipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNleadpipeActionPerformed(evt);
            }
        });

        DNwrench.setForeground(new java.awt.Color(255, 102, 102));
        DNwrench.setText("Wrench");
        DNwrench.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        DNwrench.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        DNwrench.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNwrenchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel25)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(DNwrench, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNleadpipe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNrope, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNpistol, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNcandlestick, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNknife, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNstudy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNlibrary, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNconservatory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNballroom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNhall, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNlounge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNdiningroom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNkitchen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNsuspect6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNsuspect5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNsuspect4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNsuspect3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNsuspect2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNsuspect1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DNbilliardroom))
                        .addGap(43, 43, 43))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {DNballroom, DNbilliardroom, DNcandlestick, DNconservatory, DNdiningroom, DNhall, DNkitchen, DNknife, DNleadpipe, DNlibrary, DNlounge, DNpistol, DNrope, DNstudy, DNsuspect2, DNsuspect3, DNsuspect4, DNsuspect5, DNsuspect6, DNwrench});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DNsuspect1)
                .addGap(5, 5, 5)
                .addComponent(DNsuspect2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNsuspect3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNsuspect4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNsuspect5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNsuspect6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNhall)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNlounge)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNdiningroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNkitchen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNballroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNconservatory)
                .addGap(0, 0, 0)
                .addComponent(DNbilliardroom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNlibrary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNstudy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNknife)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNcandlestick)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNpistol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNrope)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNleadpipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DNwrench)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(102, 153, 255));

        Conservatory.setText("Conservatory");
        Conservatory.setMaximumSize(new java.awt.Dimension(100, 100));
        Conservatory.setMinimumSize(new java.awt.Dimension(100, 100));
        Conservatory.setPreferredSize(new java.awt.Dimension(100, 100));
        Conservatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConservatoryActionPerformed(evt);
            }
        });

        Study.setText("Study");
        Study.setMaximumSize(new java.awt.Dimension(100, 100));
        Study.setMinimumSize(new java.awt.Dimension(100, 100));
        Study.setPreferredSize(new java.awt.Dimension(100, 100));
        Study.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudyActionPerformed(evt);
            }
        });

        Library.setText("Library");
        Library.setMaximumSize(new java.awt.Dimension(100, 100));
        Library.setMinimumSize(new java.awt.Dimension(100, 100));
        Library.setPreferredSize(new java.awt.Dimension(100, 100));
        Library.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LibraryActionPerformed(evt);
            }
        });

        Ballroom.setText("Ballroom");
        Ballroom.setMaximumSize(new java.awt.Dimension(100, 100));
        Ballroom.setMinimumSize(new java.awt.Dimension(100, 100));
        Ballroom.setPreferredSize(new java.awt.Dimension(100, 100));
        Ballroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BallroomActionPerformed(evt);
            }
        });

        BilliardRoom.setText("Billiard Room");
        BilliardRoom.setMaximumSize(new java.awt.Dimension(100, 100));
        BilliardRoom.setMinimumSize(new java.awt.Dimension(100, 100));
        BilliardRoom.setPreferredSize(new java.awt.Dimension(100, 100));
        BilliardRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BilliardRoomActionPerformed(evt);
            }
        });

        Hall.setText("Hall");
        Hall.setMaximumSize(new java.awt.Dimension(100, 100));
        Hall.setMinimumSize(new java.awt.Dimension(100, 100));
        Hall.setPreferredSize(new java.awt.Dimension(100, 100));
        Hall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HallActionPerformed(evt);
            }
        });

        Kitchen.setText("Kitchen");
        Kitchen.setMaximumSize(new java.awt.Dimension(100, 100));
        Kitchen.setMinimumSize(new java.awt.Dimension(100, 100));
        Kitchen.setPreferredSize(new java.awt.Dimension(100, 100));
        Kitchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KitchenActionPerformed(evt);
            }
        });

        DiningRoom.setText("Dining Room");
        DiningRoom.setMaximumSize(new java.awt.Dimension(100, 100));
        DiningRoom.setMinimumSize(new java.awt.Dimension(100, 100));
        DiningRoom.setPreferredSize(new java.awt.Dimension(100, 100));
        DiningRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiningRoomActionPerformed(evt);
            }
        });

        Lounge.setText("Lounge");
        Lounge.setMaximumSize(new java.awt.Dimension(100, 100));
        Lounge.setMinimumSize(new java.awt.Dimension(100, 100));
        Lounge.setPreferredSize(new java.awt.Dimension(100, 100));
        Lounge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoungeActionPerformed(evt);
            }
        });

        Hallway6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway6ActionPerformed(evt);
            }
        });

        Hallway1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway1ActionPerformed(evt);
            }
        });

        Hallway11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway11ActionPerformed(evt);
            }
        });

        Hallway12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway12ActionPerformed(evt);
            }
        });

        Hallway7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway7ActionPerformed(evt);
            }
        });

        Hallway2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway2ActionPerformed(evt);
            }
        });

        Hallway4.setMaximumSize(new java.awt.Dimension(9, 33));
        Hallway4.setMinimumSize(new java.awt.Dimension(9, 33));
        Hallway4.setPreferredSize(new java.awt.Dimension(9, 33));
        Hallway4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway4ActionPerformed(evt);
            }
        });

        Hallway3.setMaximumSize(new java.awt.Dimension(9, 33));
        Hallway3.setMinimumSize(new java.awt.Dimension(9, 33));
        Hallway3.setPreferredSize(new java.awt.Dimension(9, 33));
        Hallway3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway3ActionPerformed(evt);
            }
        });

        Hallway5.setMaximumSize(new java.awt.Dimension(9, 33));
        Hallway5.setMinimumSize(new java.awt.Dimension(9, 33));
        Hallway5.setPreferredSize(new java.awt.Dimension(9, 33));
        Hallway5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway5ActionPerformed(evt);
            }
        });

        Hallway8.setMaximumSize(new java.awt.Dimension(9, 33));
        Hallway8.setMinimumSize(new java.awt.Dimension(9, 33));
        Hallway8.setPreferredSize(new java.awt.Dimension(9, 33));
        Hallway8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway8ActionPerformed(evt);
            }
        });

        Hallway9.setMaximumSize(new java.awt.Dimension(9, 33));
        Hallway9.setMinimumSize(new java.awt.Dimension(9, 33));
        Hallway9.setPreferredSize(new java.awt.Dimension(9, 33));
        Hallway9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway9ActionPerformed(evt);
            }
        });

        Hallway10.setMaximumSize(new java.awt.Dimension(9, 33));
        Hallway10.setMinimumSize(new java.awt.Dimension(9, 33));
        Hallway10.setPreferredSize(new java.awt.Dimension(9, 33));
        Hallway10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hallway10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Hallway3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hallway4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(166, 166, 166)
                        .addComponent(Hallway5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(Hallway8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Conservatory, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Hallway11, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ballroom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(Hallway9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(39, 39, 39))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Study, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Library, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Hallway1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hallway6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(BilliardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hall, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Hallway12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hallway2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hallway7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Lounge, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(DiningRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hallway10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))))
                .addGap(61, 61, 61))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Lounge, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Hall, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hallway5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiningRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hallway10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Kitchen, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Study, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Hallway3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Library, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(Hallway1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(155, 155, 155)
                                        .addComponent(Hallway6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(Hallway4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BilliardRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Hallway8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Hallway9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Conservatory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ballroom, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(Hallway11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(Hallway2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Hallway7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(Hallway12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GameboardLayout = new javax.swing.GroupLayout(Gameboard);
        Gameboard.setLayout(GameboardLayout);
        GameboardLayout.setHorizontalGroup(
            GameboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(GameboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GameboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(GameboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(GameboardLayout.createSequentialGroup()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap()))
        );
        GameboardLayout.setVerticalGroup(
            GameboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
            .addGroup(GameboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(GameboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(GameboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(Gameboard, "card2");

        lobbyWelcome.setFont(new java.awt.Font("Old English Text MT", 0, 60)); // NOI18N
        lobbyWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lobbyWelcome.setText("Welcome:");

        startGameBox.setBackground(new java.awt.Color(153, 153, 153));
        startGameBox.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        startGamePrompt.setText("Click start when you are ready to play!");

        startGamePrompt1.setText("Note: you need at least 3 players");

        startGameButton.setText("START GAME!!");
        startGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout startGameBoxLayout = new javax.swing.GroupLayout(startGameBox);
        startGameBox.setLayout(startGameBoxLayout);
        startGameBoxLayout.setHorizontalGroup(
            startGameBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startGameBoxLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(startGameBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startGamePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startGameBoxLayout.createSequentialGroup()
                        .addComponent(startGamePrompt1)
                        .addGap(28, 28, 28)))
                .addGap(46, 46, 46))
            .addGroup(startGameBoxLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(startGameButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        startGameBoxLayout.setVerticalGroup(
            startGameBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startGameBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startGamePrompt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startGamePrompt1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startGameButton)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Players currently in the game:");

        playersInLobby.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        playersInLobby.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(playersInLobby);

        javax.swing.GroupLayout LobbyLayout = new javax.swing.GroupLayout(Lobby);
        Lobby.setLayout(LobbyLayout);
        LobbyLayout.setHorizontalGroup(
            LobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LobbyLayout.createSequentialGroup()
                .addGroup(LobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LobbyLayout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(LobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lobbyWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LobbyLayout.createSequentialGroup()
                        .addGap(417, 417, 417)
                        .addComponent(startGameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        LobbyLayout.setVerticalGroup(
            LobbyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LobbyLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(lobbyWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(startGameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        getContentPane().add(Lobby, "card4");

        jLabel7.setFont(new java.awt.Font("Old English Text MT", 0, 60)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Congratulations! You've won!!");

        javax.swing.GroupLayout WinningLayout = new javax.swing.GroupLayout(Winning);
        Winning.setLayout(WinningLayout);
        WinningLayout.setHorizontalGroup(
            WinningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(WinningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WinningLayout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );
        WinningLayout.setVerticalGroup(
            WinningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
            .addGroup(WinningLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(WinningLayout.createSequentialGroup()
                    .addGap(420, 420, 420)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );

        getContentPane().add(Winning, "card5");

        jLabel9.setFont(new java.awt.Font("Old English Text MT", 0, 60)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sorry! You lost the game.. ");

        javax.swing.GroupLayout LosingLayout = new javax.swing.GroupLayout(Losing);
        Losing.setLayout(LosingLayout);
        LosingLayout.setHorizontalGroup(
            LosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1226, Short.MAX_VALUE)
            .addGroup(LosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LosingLayout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(234, Short.MAX_VALUE)))
        );
        LosingLayout.setVerticalGroup(
            LosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 885, Short.MAX_VALUE)
            .addGroup(LosingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LosingLayout.createSequentialGroup()
                    .addGap(420, 420, 420)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(420, Short.MAX_VALUE)))
        );

        getContentPane().add(Losing, "card6");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DNsuspect2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNsuspect2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNsuspect2ActionPerformed

    private void DNsuspect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNsuspect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNsuspect1ActionPerformed

    private void DNsuspect4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNsuspect4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNsuspect4ActionPerformed

    private void DNsuspect5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNsuspect5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNsuspect5ActionPerformed

    private void DNsuspect3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNsuspect3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNsuspect3ActionPerformed

    private void DNsuspect6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNsuspect6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNsuspect6ActionPerformed

    private void DNhallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNhallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNhallActionPerformed

    private void DNloungeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNloungeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNloungeActionPerformed

    private void DNdiningroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNdiningroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNdiningroomActionPerformed

    private void DNkitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNkitchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNkitchenActionPerformed

    private void DNballroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNballroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNballroomActionPerformed

    private void DNconservatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNconservatoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNconservatoryActionPerformed

    private void DNbilliardroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNbilliardroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNbilliardroomActionPerformed

    private void DNlibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNlibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNlibraryActionPerformed

    private void DNstudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNstudyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNstudyActionPerformed

    private void DNknifeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNknifeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNknifeActionPerformed

    private void DNcandlestickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNcandlestickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNcandlestickActionPerformed

    private void DNpistolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNpistolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNpistolActionPerformed

    private void DNropeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNropeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNropeActionPerformed

    private void DNleadpipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNleadpipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNleadpipeActionPerformed

    private void DNwrenchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNwrenchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DNwrenchActionPerformed

    private void ConservatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConservatoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConservatoryActionPerformed

    private void StudyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudyActionPerformed

    private void LibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LibraryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LibraryActionPerformed

    private void BallroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BallroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BallroomActionPerformed

    private void BilliardRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BilliardRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BilliardRoomActionPerformed

    private void HallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HallActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HallActionPerformed

    private void KitchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KitchenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KitchenActionPerformed

    private void DiningRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiningRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiningRoomActionPerformed

    private void LoungeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoungeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoungeActionPerformed

    private void Hallway6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway6ActionPerformed

    private void Hallway1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway1ActionPerformed

    private void Hallway11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway11ActionPerformed

    private void Hallway12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway12ActionPerformed

    private void Hallway7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway7ActionPerformed

    private void Hallway2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway2ActionPerformed

    private void Hallway4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway4ActionPerformed

    private void Hallway3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway3ActionPerformed

    private void Hallway5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway5ActionPerformed

    private void Hallway8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway8ActionPerformed

    private void Hallway9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway9ActionPerformed

    private void Hallway10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hallway10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hallway10ActionPerformed

    private void startNewGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startNewGameButtonActionPerformed
        //Send a new game message to the backend
        gameID = clueLess.startNewGame();
        GameOps.setVisible(false);
        gameIDfield.setVisible(false);
        gameIDprompt.setVisible(false);
        startNewGameButton.setVisible(false);
        EnterUserID.setVisible(true);
        userIDfield.setVisible(true);
    }//GEN-LAST:event_startNewGameButtonActionPerformed

    private void gameIDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gameIDfieldActionPerformed
        // Send Game ID to join a game. Need to verify that the game code is valid
        System.out.println(evt.getActionCommand());
        gameID = Integer.parseInt(gameIDfield.getText());
        clueLess.joinGame(gameID);
        GameOps.setVisible(false);
        gameIDfield.setVisible(false);
        gameIDprompt.setVisible(false);
        startNewGameButton.setVisible(false);
        EnterUserID.setVisible(true);
        userIDfield.setVisible(true);
    }//GEN-LAST:event_gameIDfieldActionPerformed

    private void userIDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userIDfieldActionPerformed
        // TODO add your handling code here:
        userID = userIDfield.getText();
        clueLess.sendUserName(userID);
        switchScreens("Lobby");
        lobbyWelcome.setText("Welcome: "+ userID);
    }//GEN-LAST:event_userIDfieldActionPerformed

    private void startGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameButtonActionPerformed
        // TODO add your handling code here:
        switchScreens("GameBoard");
    }//GEN-LAST:event_startGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
                
            }
        });
    }
    
    public void addPlayer(String playerName){
        //playersInLobby.add();
        System.out.println("Need to add function to add players to lobby list");
    }
    
    /**
     * This function initializes the suspect list with the player names and 
     * updates the cards shown for each user to reflect those dealt to them.
     * @param GB 
     */
    public void setupGameBoard(String[] suspect,String cards[]){
        
        this.jTextArea1.setEditable(false);
        this.jTextArea1.setText("Setting up everything for you :)");
        
        // Initialize the suspect list in Detective Notes
        this.DNsuspect1.setText(suspect[0]);
        this.DNsuspect2.setText(suspect[1]);
        this.DNsuspect3.setText(suspect[2]);
        this.DNsuspect4.setText(suspect[3]);
        this.DNsuspect5.setText(suspect[4]);
        this.DNsuspect6.setText(suspect[5]);
        
        // Display cards given to the user
        //String cards[] = {"Conservatory","Rope","Mrs. Maraple","Dragons"};
        this.jList1.setListData(cards);
    }
    
    
    public void switchScreens(String screenID){
        switch(screenID){
            case "Lobby":
                Lobby.setVisible(true);
                Gameboard.setVisible(false);
                Welcome.setVisible(false);
                Winning.setVisible(false);
                Losing.setVisible(false);
                break;
            case "GameBoard":
                Gameboard.setVisible(true);
                Lobby.setVisible(false);
                Welcome.setVisible(false);
                Winning.setVisible(false);
                Losing.setVisible(false);
                break;
            case "Welcome":
                Welcome.setVisible(true);
                Lobby.setVisible(false);
                Gameboard.setVisible(false);
                Winning.setVisible(false);
                Losing.setVisible(false);
                // set all the fields on welcome screen to visible as appropriate
                EnterUserID.setVisible(false);
                userIDfield.setVisible(false);
                GameOps.setVisible(true);
                gameIDfield.setVisible(true);
                gameIDprompt.setVisible(true);
                startNewGameButton.setVisible(true);
                break;
            case "Winning":
                Winning.setVisible(true);
                Lobby.setVisible(false);
                Gameboard.setVisible(false);
                Welcome.setVisible(false);
                Losing.setVisible(false);
                break;
            case "Losing":
                Losing.setVisible(true);
                Lobby.setVisible(false);
                Gameboard.setVisible(false);
                Welcome.setVisible(false);
                Winning.setVisible(false);
                break;
            default:
                break;
        }
    }
    
    /**
     * This function takes the room ID and activates the buttons corresponding
     * to the valid locations a player may move.
     * @param roomID 
     */
    public void openRoomSelection(int roomID){
        switch(roomID){
            case 1: 
                Study.setEnabled(true);
                break;
            case 2: 
                Hallway1.setEnabled(true);
                break;
            case 3:
                Hall.setEnabled(true);
                break;
            case 4:
                Hallway2.setEnabled(true);
                break;
            case 5:
                Lounge.setEnabled(true);
                break;
            case 6:
                Hallway3.setEnabled(true);
                break;
            case 7:
                Hallway4.setEnabled(true);
                break;
            case 8:
                Hallway5.setEnabled(true);
                break;
            case 9:
                Library.setEnabled(true);
                break;
            case 10:
                Hallway6.setEnabled(true);
                break;
            case 11:
                BilliardRoom.setEnabled(true);
                break;
            case 12:
                Hallway7.setEnabled(true);
                break;
            case 13:
                DiningRoom.setEnabled(true);
                break;
            case 14:
                Hallway8.setEnabled(true);
                break;
            case 15:
                Hallway9.setEnabled(true);
                break;
            case 16:
                Hallway10.setEnabled(true);
                break;
            case 17:
                Conservatory.setEnabled(true);
                break;
            case 18:
                Hallway11.setEnabled(true);
                break;
            case 19:
                Ballroom.setEnabled(true);
                break;
            case 20:
                Hallway12.setEnabled(true);
                break;
            case 21:
                Kitchen.setEnabled(true);
                break;
            default: System.out.println("That is not a valid room code. \n");
                break;
            
        }
            
    }
    
    /**
     * This function disables all of the map buttons after the user has selected
     * their move. This prevents the user from moving when it's not their turn.
     */
    private void closeRoomSelection(){
        Study.setEnabled(false);
        Hallway1.setEnabled(false);
        Hall.setEnabled(false);
        Hallway2.setEnabled(false);
        Lounge.setEnabled(false);
        Hallway3.setEnabled(false);
        Hallway4.setEnabled(false);
        Hallway5.setEnabled(false);
        Library.setEnabled(false);
        Hallway6.setEnabled(false);
        BilliardRoom.setEnabled(false);
        Hallway7.setEnabled(false);
        DiningRoom.setEnabled(false);
        Hallway8.setEnabled(false);
        Hallway9.setEnabled(false);
        Hallway10.setEnabled(false);
        Conservatory.setEnabled(false);
        Hallway11.setEnabled(false);
        Ballroom.setEnabled(false);
        Hallway12.setEnabled(false);
        Kitchen.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ballroom;
    private javax.swing.JButton BilliardRoom;
    private javax.swing.JButton Conservatory;
    private javax.swing.JCheckBox DNballroom;
    private javax.swing.JCheckBox DNbilliardroom;
    private javax.swing.JCheckBox DNcandlestick;
    private javax.swing.JCheckBox DNconservatory;
    private javax.swing.JCheckBox DNdiningroom;
    private javax.swing.JCheckBox DNhall;
    private javax.swing.JCheckBox DNkitchen;
    private javax.swing.JCheckBox DNknife;
    private javax.swing.JCheckBox DNleadpipe;
    private javax.swing.JCheckBox DNlibrary;
    private javax.swing.JCheckBox DNlounge;
    private javax.swing.JCheckBox DNpistol;
    private javax.swing.JCheckBox DNrope;
    private javax.swing.JCheckBox DNstudy;
    private javax.swing.JCheckBox DNsuspect1;
    private javax.swing.JCheckBox DNsuspect2;
    private javax.swing.JCheckBox DNsuspect3;
    private javax.swing.JCheckBox DNsuspect4;
    private javax.swing.JCheckBox DNsuspect5;
    private javax.swing.JCheckBox DNsuspect6;
    private javax.swing.JCheckBox DNwrench;
    private javax.swing.JButton DiningRoom;
    private javax.swing.JPanel EnterUserID;
    private javax.swing.JPanel GameOps;
    private javax.swing.JPanel Gameboard;
    private javax.swing.JButton Hall;
    private javax.swing.JButton Hallway1;
    private javax.swing.JButton Hallway10;
    private javax.swing.JButton Hallway11;
    private javax.swing.JButton Hallway12;
    private javax.swing.JButton Hallway2;
    private javax.swing.JButton Hallway3;
    private javax.swing.JButton Hallway4;
    private javax.swing.JButton Hallway5;
    private javax.swing.JButton Hallway6;
    private javax.swing.JButton Hallway7;
    private javax.swing.JButton Hallway8;
    private javax.swing.JButton Hallway9;
    private javax.swing.JButton Kitchen;
    private javax.swing.JButton Library;
    private javax.swing.JPanel Lobby;
    private javax.swing.JPanel Losing;
    private javax.swing.JButton Lounge;
    private javax.swing.JButton Study;
    private javax.swing.JPanel Welcome;
    private javax.swing.JPanel Winning;
    private javax.swing.JTextField gameIDfield;
    private javax.swing.JLabel gameIDprompt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JLabel lobbyWelcome;
    private javax.swing.JList<String> playersInLobby;
    private javax.swing.JPanel startGameBox;
    private javax.swing.JButton startGameButton;
    private javax.swing.JLabel startGamePrompt;
    private javax.swing.JLabel startGamePrompt1;
    private javax.swing.JButton startNewGameButton;
    private javax.swing.JTextField userIDfield;
    private javax.swing.JLabel userIDprompt;
    // End of variables declaration//GEN-END:variables
}
